//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EOTAEntities : DbContext
    {
        public EOTAEntities()
            : base("name=EOTAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<Discount_Calculator> Discount_Calculators { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Feedback_overview> Feedback_overviews { get; set; }
        public virtual DbSet<Institute_Info> Institute_Infoes { get; set; }
        public virtual DbSet<Institute_Paymnt> Institute_Paymnts { get; set; }
        public virtual DbSet<Mock_Test> Mock_Tests { get; set; }
        public virtual DbSet<Paid_Cours> Paid_Courses { get; set; }
        public virtual DbSet<Paid_Courses_Certificates> Paid_Courses_Certificates { get; set; }
        public virtual DbSet<Post_Cours> Post_Courses { get; set; }
        public virtual DbSet<Reference_Calculator> Reference_Calculators { get; set; }
        public virtual DbSet<Tbl_ADMN> Tbl_ADMN { get; set; }
        public virtual DbSet<Tbl_Cand_Main> Tbl_Cand_Main { get; set; }
        public virtual DbSet<Tbl_Doc> Tbl_Doc { get; set; }
        public virtual DbSet<Tbl_Trainers> Tbl_Trainers { get; set; }
        public virtual DbSet<Tbl_Video> Tbl_Video { get; set; }
        public virtual DbSet<Trainer> Trainers { get; set; }
        public virtual DbSet<Use_Mock_Test> Use_Mock_Tests { get; set; }
        public virtual DbSet<Use_Test_counter> Use_Test_counters { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Courses_Trainers> Courses_Trainers { get; set; }
    }
}
