//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ADMIN
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide Admin Id")]
        [Display(Name = "Admin id")]
        [DataType(DataType.Password)]
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide Admin Name")]
        [Display(Name = "Admin Name")]
        public string Name { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide Email Id")]
        [Display(Name = "Email id")]
        public string EmailId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide Admin Number")]
        [Display(Name = "Admin PH.Number")]
        public string Number { get; set; }


        public string Image_Path { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide a valid Password")]
        [Display(Name = "Admin Password")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Minimum 6 characters required")]
        public string Password { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide password again")]
        [Display(Name = "Admin Confirm password")]
        [DataType(DataType.Password)]
        [Compare("Admin_Pass", ErrorMessage = "password and confirm password do not match")]
        public string Re_Password { get; set; }

        public string Admin_ResetPassCode { get; set; }


        public Nullable<bool> IsEmailVerified { get; set; }


        public Nullable<System.Guid> ActivationCode { get; set; }

        public HttpPostedFileBase image { get; set; }


        [Display(Name = "Remember me")]
        public bool rememberMe { get; set; }

    }
}
