//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Courses_Trainers
    {
        public int id { get; set; }
        public Nullable<int> Course_code { get; set; }
        public string Name { get; set; }
        public string Course_name { get; set; }
        public string Occupation { get; set; }
        public string Biography { get; set; }
        public string Image { get; set; }

        public HttpPostedFileBase TrnrImage { get; set; }
    }
}
