
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Institute_Paymnt
    {
        public int Id { get; set; }
        public string Institute_Id { get; set; }
        public Nullable<bool> IsPaid_ { get; set; }
        public string Course_Code { get; set; }
    }
}
