//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Institute_Info
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Institute Id")]
        [Display(Name = "Institute Code")]
        public string Institute_Id { get; set; }

        [Display(Name = "Institute Name")]
        public string Institute_Name_ { get; set; }
        [DataType(DataType.MultilineText)]
        [Display(Name = "Location")]
        public string Location { get; set; }

        [Display(Name = "Discount Code")]
        public string Promocode { get; set; }

        [Display(Name = "Discount Percent")]
        public string Discount_Percent { get; set; }
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                         @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                         @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                         ErrorMessage = "Email is not valid")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide email Id")]
        public string Email { get; set; }
        public Nullable<bool> IsHOD { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public bool option { get; set; }
    }
}

