//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Mock_Test
    {
        public int Id { get; set; }
        [Display(Name = "Exam Code")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Exam code")]
        public string Exam_Code { get; set; }
        [Display(Name = "Course Code")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide course code")]
        public string Course_Code { get; set; }
        [Display(Name = "Ques. Type")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Q-type")]
        public string Question_Type { get; set; }
        [Display(Name = "Ques. no.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Ques. no.")]
        public Nullable<int> Ques_No { get; set; }
        [Display(Name = "Question")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide question")]
        public string Question { get; set; }
        [Display(Name = "First Op.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide First Op.")]
        public string Option1 { get; set; }
        [Display(Name = "Second Op.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Second Op.")]
        public string Option2 { get; set; }
        [Display(Name = "Third Op.")]
        public string Option3 { get; set; }
        [Display(Name = "Fourth Op.")]
        public string Option4 { get; set; }
        [Display(Name = "Fifth Op.")]
        public string Option5 { get; set; }
        [Display(Name = "Sixth Op.")]
        public string Option6 { get; set; }
        [Display(Name = "Currect Op.")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Currect Op.")]
        public string Currect_Option { get; set; }

        public Nullable<bool> EnableDisable { get; set; }
        [Display(Name = "Exam Time")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Exam Time")]
        public string Exam_Time { get; set; }
        [Display(Name = "Exam posting Date")]
        public Nullable<System.DateTime> Exam_Posting_Date { get; set; }
        //public bool Checked { get; set; }
        public bool Optio1 { get; set; }
        public bool Optio2 { get; set; }
        public bool Optio3 { get; set; }
        public bool Optio4 { get; set; }
        public bool Optio5 { get; set; }
        public bool Optio6 { get; set; }
        public string Checked { get; set; }

        [DataType(DataType.MultilineText)]
        public string Textbx { get; set; }
        public Nullable<bool> IsMocktest { get; set; }

        [Display(Name = "Pass mark")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Pass mark")]
        public Nullable<int> Pass_mark { get; set; }
    }
}

