//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Paid_Cours
    {
        public int id { get; set; }
        public Nullable<int> Course_Code { get; set; }
        public string Course_Name { get; set; }
        public Nullable<int> User_id { get; set; }
        public string User_EmailId { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    }
}


