//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Post_Cours
    {
        public int Id { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public Nullable<int> Trainer_Id { get; set; }
        public Nullable<int> User_Id { get; set; }

        //[Required(AllowEmptyStrings = false, ErrorMessage = "Please provide course title")]
        public string Title { get; set; }

        [DataType(DataType.MultilineText)]
        public string Learning_Point { get; set; }
        public string Learning_Point1 { get; set; }
        public string Learning_Point2 { get; set; }
        public string Learning_Point3 { get; set; }
        public string Learning_Point4 { get; set; }
        public string Learning_Point5 { get; set; }
        public string Requirements { get; set; }
        public string Requirement1 { get; set; }
        public string Requirement2 { get; set; }
        public string Requirement3 { get; set; }

        [DataType(DataType.MultilineText)]
        public string Small_Description { get; set; }

        [DataType(DataType.MultilineText)]
        public string Brief_Description { get; set; }

        //[Required(AllowEmptyStrings = false, ErrorMessage = "Please provide course price")]
        public string New_Price { get; set; }

        public string Old_Price { get; set; }

        [Display(Name = "Video Title")]
        public string Video_Title { get; set; }

        [Display(Name = "Video")]
        public string Video_Url { get; set; }

        //[Required(AllowEmptyStrings = false, ErrorMessage = "Please select video file/s")]
        public HttpPostedFileBase VidFile { get; set; }
        public HttpPostedFileBase DemoFile { get; set; }
        public string Document_Image { get; set; }

        //[Required(AllowEmptyStrings = false, ErrorMessage = "Please select image file")]
        public HttpPostedFileBase Docimage { get; set; }

        //[Required(AllowEmptyStrings = false, ErrorMessage = "Please select course type")]
        public string Course_Type { get; set; }

        public Nullable<int> Secret_Code { get; set; }

        // [Required(AllowEmptyStrings = false, ErrorMessage = "Please select uploader")]
        public string upldr { get; set; }
        public string upldrid { get; set; }

        public string upldrpss { get; set; }

        public Nullable<bool> EnableDisable { get; set; }
        public string disable { get; set; }

        public string enable { get; set; }



        public string Course_name { get; set; }
        public Nullable<int> Chapter_number { get; set; }
        public string Description { get; set; }
        public string Demo_video_Path { get; set; }
        public string Course_Image { get; set; }

        //for trainer=============================================

        public Nullable<int> Course_code { get; set; }
        public string Name { get; set; }
        public string Coursename { get; set; }
        public string Occupation { get; set; }
        public string Biography { get; set; }
        public HttpPostedFileBase TrnrImage { get; set; }
    }
}

