//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reference_Calculator
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a reference code")]
        public string Reference_Code { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public Nullable<int> Trainer_Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a discount percentage")]
        public string Referral_Discount_Price { get; set; }
        public Nullable<bool> EnableDisable { get; set; }

        public string upldr { get; set; }
        public string upldrid { get; set; }
        public string upldrpss { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide User email")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                         @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                         @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                         ErrorMessage = "Email is not valid")]
        public string EmailId { get; set; }

        [DataType(DataType.MultilineText)]
        public string msgbox { get; set; }
    }
}



