//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Tbl_Video
    {

        [Display(Name = "Video Id")]
        public int Video_id { get; set; }

        [Display(Name = "Video Title")]
        public string Video_Title { get; set; }

        [Display(Name = "Video")]
        public string Video_Path { get; set; }
        public byte[] Video { get; set; }
        public HttpPostedFileBase VidFile { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}

