
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class Tbl_Cand_Main
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide your user Id")]
        [Display(Name = "Candidate id")]
        [DataType(DataType.Password)]
        public int Cand_id { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide user name")]
        [Display(Name = "Name")]
        public string CandName { get; set; }

        //[DataType(DataType.EmailAddress)]
        //[Required(AllowEmptyStrings = false, ErrorMessage = "please provide Email Id")]
        [Required(ErrorMessage = "Email is Required")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                          @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                          @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                          ErrorMessage = "Email is not valid")]

        [Display(Name = "Email")]
        public string Cand_EmailId { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide Candidate Number")]
        [Display(Name = "Phone Number")]
        public string Cand_MNum { get; set; }

        [Display(Name = "Photo Title")]
        public string Cand_PicTitle { get; set; }

        [Display(Name = "Select Photo")]
        public string Cand_ImagePath { get; set; }

        [Display(Name = "Document Name")]
        public string Cand_DocTitle { get; set; }

        [Display(Name = "Select Document")]
        public string Cand_DocPath { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide a valid Password")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Password must be minimum 6 characters")]
        [RegularExpression("(?!^[0-9]*$)(?!^[a-zA-Z]*$)^([a-zA-Z0-9]{8,16})$", ErrorMessage = "Password must be between 8 to 16 characters,contain at least one digit and one alphabetic character and must not contain special characters")]
        [AllowHtml]
        public string Cand_Pass { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide re-password")]
        [Display(Name = "Confirm password")]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Compare("Cand_Pass", ErrorMessage = "Password and confirm password do not match")]
        [RegularExpression("^[a-zA-Z0-9]*$", ErrorMessage = "Re-password must contain only alphabets and numbers")]
        [AllowHtml]
        public string Cand_RePass { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string Cand_ResetPassCode { get; set; }
        public Nullable<bool> Cand_IsEmailVerified { get; set; }
        public Nullable<System.Guid> Cand_ActivationCode { get; set; }

        public Nullable<System.Guid> cand_ReferenceCode { get; set; }
        public HttpPostedFileBase image { get; set; }

        public HttpPostedFileBase DocFile { get; set; }
        [Display(Name = "Friend's Email")]
        public string inputEmail { get; set; }

        [Display(Name = "Remember me")]
        public bool rememberMe { get; set; }
        //[Required(AllowEmptyStrings = false, ErrorMessage = "Please select certificate")]
        public HttpPostedFileBase Certificate { get; set; }

        [DataType(DataType.MultilineText)]
        public string msgbox { get; set; }

        public string CRSTP { get; set; }

        public string Address { get; set; }

        //public PagedList.IPagedList<EtreetrainingUser.Models.Post_Cours> ss { get; set; }
    }
}

