//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Tbl_Doc
    {
        [Display(Name = "Document Id")]
        public int Doc_id { get; set; }

        [Display(Name = "Document Title")]
        public string Doc_Title { get; set; }

        [Display(Name = "Document/Document Path")]
        public string Doc_Path { get; set; }

        [Display(Name = "Image for Document")]
        public string Doc_ImagePath { get; set; }

        public HttpPostedFileBase DocFile { get; set; }
        public HttpPostedFileBase Docimage { get; set; }
    }
}

