//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Trainer
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide Trainer Id")]
        [Display(Name = "Trainer id")]
        [DataType(DataType.Password)]
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Name")]

        public string Name { get; set; }

        [Required(ErrorMessage = "Please provide email")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                        @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                        @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                        ErrorMessage = "Email is not valid")]

        [Display(Name = "Email ID")]

        public string Email_Id { get; set; }

        [DataType(DataType.PhoneNumber)]
        [MinLength(10, ErrorMessage = "Phone number should be minimim 10 digits")]
        [MaxLength(10, ErrorMessage = "Phone number should be maximum 10 digits")]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }

        [Display(Name = "Photo Title")]
        public string Photo_Title { get; set; }

        [Display(Name = "Upload Photo")]
        public string Photo_Path { get; set; }



        [Required(AllowEmptyStrings = false, ErrorMessage = "Please provide Password")]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [MinLength(6, ErrorMessage = "Password must be minimum 6 characters")]


        [RegularExpression("(?!^[0-9]*$)(?!^[a-zA-Z]*$)^([a-zA-Z0-9]{8,16})$", ErrorMessage = "Password must be between 8 to 16 characters,contain at least one digit and one alphabetic character and must not contain special characters")]

        [System.Web.Mvc.AllowHtml]
        public string Password { get; set; }

        [Required(AllowEmptyStrings = false, ErrorMessage = "please provide re-password")]
        [Display(Name = "Re-Password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "password and confirm password do not match")]
        [System.Web.Mvc.AllowHtml]
        public string Re_Password { get; set; }
        public bool rememberMe { get; set; }
        //[Required(AllowEmptyStrings = false, ErrorMessage = "Please provide image")]
        public HttpPostedFileBase image { get; set; }

        public Nullable<bool> IsActive { get; set; }
    }
}

