//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Use_Test_counter
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Exam_Code { get; set; }
        public string Course_Code { get; set; }
        public Nullable<int> Exam_Secretcode { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public string Exam_Time { get; set; }
        public string Remaining_Time { get; set; }
        public Nullable<bool> IsFinished { get; set; }
    }
}

