//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtreetrainingUser.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Use_Mock_Test
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string User_Email { get; set; }
        public string Exam_Code { get; set; }
        public string Course_Code { get; set; }
        public Nullable<int> Ques_No { get; set; }
        public string Choosed_Option { get; set; }
        public Nullable<decimal> Marks { get; set; }
        public Nullable<System.DateTime> Exam_Date { get; set; }

        public string Checked { get; set; }

        public Nullable<int> Exam_Secretcode { get; set; }
    }
}
